### PR TITLE
Graphite reactor - Fixes #8

### LINKED ISSUE #8: Graphite Reactor
Graphite reactor would store information in Graphite.

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by indexzero** [comment]
@obazoud Could you explain how this works a little more to me? I don't know _anything_ about graphite and I'd like to learn.

cc/ @dscape @jhs

**Comment by obazoud** [comment]
[Graphite](http://graphite.wikidot.com/) has 3 individual components
- Carbon: a daemon that listens incoming data (metric) and store numeric time-series data in whisper files
- Graphite-web: render graphs in browser
- Whisper: is a fixed-size database
  Graphite is based on "push" not "pull".

A simple way to send metrics (TCP or UDP):

``` shell
echo "<metric path> <metric value> <metric timestamp>" | nc $SERVER $PORT
echo "myserver.load.1m 4 `date +%s`" | nc 127.0.0.1 2003
echo "myserver.load.5m 4 `date +%s`" | nc 127.0.0.1 2003
echo "myserver.load.15m 4 `date +%s`" | nc 127.0.0.1 2003
```

metric path: a metric path that be renderer as a tree

``` shell
.
└── myserver
    └── load
        └── 1m
        └── 5m
        └── 15m
```

metric value: an integer or a float
metric timestamp: a UNIX timestamp

Graphite (web) are some very nice features:
- easy to add few metrics in a graph, create dashboard
- apply fonction like : percent, average, derivative, integral, nPercentile, timeShift (my favorite:)), ...
- export data as json
- export data as image

My reactor is to send metric based on data event to Graphite.
- A best practice is to prefix metric by environment (or that ever you want) what why I add this option.
- metric name will be <prefix>.<host>.<service>.<state> and I replace '.' by '_' in host and service

For example with the following event and prefix = "production."

``` javascript
{ host: 'app.server.com',
  service: 'app.server2/health/heartbeat',
  state: 'up',
  time: 1360523052932,
  description: 'No description',
  tags: [],
  metric: 1,
  ttl: 3000 }
```

metric name will be "production.app_server_com.app_server.health.heartbeat.up"
metric value is 1
metric timestamp is 1360523052932

**Comment by indexzero** [comment]
@obazoud Why the string replacement in metric names?

**Comment by obazoud** [comment]
@indexzero I replace '.' by '_' to have a better layout in, Graphite.
Graphite creates a directory each time it finds a '.'
I create a metric by state.

Without replacement:
graphite2-without-remplacement
With replacement:
graphite-with-replacement

**Comment by mwawrusch** [comment]
@obazoud do you mind posting your godot server on a gist, I need to implement a simple godot - graphite bridge and don't want to reinvent the wheel.

**Comment by indexzero** [comment]
Cherry-picked. Thanks!

**Comment by obazoud** [comment]
@mwawrusch You have an example https://github.com/nodejitsu/godot/blob/master/lib/godot/reactor/graphite.js#L8

You can find a lot of stuff (still in progress) about gobot at https://github.com/organizations/godot-plugins
including Graphite Producer at https://github.com/godot-plugins/godot-graphite

**Comment by mwawrusch** [comment]
Awesome, thank you.

On Sat, Mar 23, 2013 at 1:15 PM, Olivier Bazoud notifications@github.comwrote:

> @mwawrusch https://github.com/mwawrusch You have an example
> https://github.com/nodejitsu/godot/blob/master/lib/godot/reactor/graphite.js#L8
> 
> You can find a lot of stuff (still in progress) about gobot at
> https://github.com/organizations/godot-plugins
> including Graphite Producer at
> https://github.com/godot-plugins/godot-graphite
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodejitsu/godot/pull/27#issuecomment-15343947
> .

## 

Martin Wawrusch
p: +1 310 404 1698

modeista.com - Connect With Style

I blog at http://martinatsunset.com : O API Marketplace, Where Art Thou
Follow me on twitter at @martin_sunset http://twitter.com/martin_sunset

**Pull request closed without merging**
