### PR TITLE
An IRC reactor implementation

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by mmalecki** [comment]
Wow, you are awesome. Did you take a look at `ircb`? It happens to have better error handling than `irc` module.
Anyway, I'll test this one out today/tomorrow.

**Comment by dscape** [comment]
:+1:

**Comment by indexzero** [comment]
This is great, but it should have tests :) 

@obazoud feel free to mock them.

**Comment by indexzero** [comment]
@obazoud Any thoughts on `ircb`? It's easier for us to make changes to that than `irc` because it's maintained by @mmalecki

**Comment by indexzero** [comment]
Also thinking if we want to add the dependency bloat here. Might be more useful as `godot-irc`. Not 100% positive about that. @dscape @mmalecki your thoughts?

**Comment by mmalecki** [comment]
Yeah, `godot-irc` is nicer IMO.

**Comment by obazoud** [comment]
Ok I an changing to ircb.
@mmalecki could you release ircb with commit efbc14b

**Comment by cdesiles** [comment]
What's up with this reactor? Is some help required?

**Comment by jcrugzz** [comment]
@jokesterfr I believe the consideration was if we should pull this out into a separate module or not and I am more inclined to think that is a good idea. This currently isn't easy in the current form so there will be some things to consider. There will be more info about this soon :).

**Comment by obazoud** [comment]
@jokesterfr IRC Reator is also available as separate module : https://github.com/godot-plugins/godot-ircb

**Comment by indexzero** [comment]
@obazoud Oh great you pulled that out into it's own module. I'm going to close this since it really belongs in a separate module.

Would love to have your work in `godot-plugins` in the main `godot` README if you could open a PR.

**Pull request closed without merging**
